/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package netty.server;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  @SuppressWarnings("PMD.SystemPrintln")
  public static void main(final String[] args) {
    System.out.println(new App().getGreeting());
  }
}
